### ISSUE TITLE
In home page, when we click on the quick view then select the variant then the successfull message is coming of green colour is not designed properly, it can be improved.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#1]
**Actual result:**
In home page, when we click on the quick view then select the variant then the successfull message is coming of green colour is not designed properly, it can be improved.
![image](https://user-images.githubusercontent.com/102131636/178435749-b834400c-e4a8-43ad-a804-ae75a7bbba06.png)

**Expected result:**
The successfull message should be designed properly.

**Comment by ui-amankumar** [comment]
It is fixed @sudhanshu0603

**Comment by sudhanshu0603** [comment]
ok, resolved
