### ISSUE TITLE
When we are clicking on the search input field then it is shifting to the left side.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#10]
**Actual result:**
When we are clicking on the search input field then it is shifting to the left side.
https://www.awesomescreenshot.com/video/9920315?key=c1a738a98e3b7afb0602b652ed531c49

**Expected result:**
The search input field must be designed well.

**Comment by devAbhishekYadav** [comment]
@ui-amankumar I have made the changes as you told me to do

**Comment by devAbhishekYadav** [comment]
@sudhanshu0603 you can test

**Comment by sudhanshu0603** [comment]
ok, resolved
