### ISSUE TITLE
Wishlist icon is not added in the mobile view.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#11]
**Actual result:**
Wishlist icon is not added in the mobile view.
**Expected result:**
The wishlist have to be added for the mobile view.

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/178475646-d3f497fd-4585-4e02-ab4f-9d4e632403a9.png)
wishlist coming

**Comment by sudhanshu0603** [comment]
ok
