### ISSUE TITLE
In search page, the quick view is added below the image in live and missing in preview.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#2]
**Actual result:**
In search page, the quick view is added below the image in live and missing in preview.
Preview: https://6twjdjydwbn6o7tw-24740200527.shopifypreview.com/search?q=shirt
![image](https://user-images.githubusercontent.com/102131636/178438236-3dd4c3b3-01a4-46af-b8c6-916d6aabdc61.png)

**Expected result:**
The quick view  must be added in  preview.
![image](https://user-images.githubusercontent.com/102131636/178438350-c59695f2-2a4a-4d9a-90b9-52fc86f2bde8.png)

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/178474953-72c916ec-d181-4156-8c2c-78be9258fee7.png)
modified as per client requirement

**Comment by sudhanshu0603** [comment]
ok, resolved
