### ISSUE TITLE
The search bar, icon is not coming in the middle.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#3]
**Actual result:**
The search bar, icon is not coming in the middle.
Preview: https://6twjdjydwbn6o7tw-24740200527.shopifypreview.com/search?q=shirt 
![image](https://user-images.githubusercontent.com/102131636/178438964-6aecd582-eea7-44f1-8165-ee60e8a13de3.png)

**Expected result:**
The search icon have to come in the middle.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 It is fixed.

**Comment by sudhanshu0603** [comment]
ok, resolved
