### ISSUE TITLE
In header navigation, when we hover over the T-SHIRTS navation then submenu are disappearing when we are coming down.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#5]
**Actual result:**
In header navigation, when we hover over the T-SHIRTS navation then submenu are disappearing when we are coming down.
The video: https://www.awesomescreenshot.com/video/9918249?key=e52b39701e60c947235baa5c9c0b6221 
![image](https://user-images.githubusercontent.com/102131636/178447491-3a23ee21-69cb-4574-81f2-1500a2a79d2e.png)

**Expected result:**
When we hover on the T-shirts and when we want to select its dropdown it must be clickable.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 fixed.

**Comment by sudhanshu0603** [comment]
ok, resolved
