### ISSUE TITLE
When we are clicking any Navigation then the square box is coming on the dropdown of the T-shirt.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#6]
**Actual result:**
When we are clicking any Navigation then the square box is coming on the dropdown of the T-shirt.
![image](https://user-images.githubusercontent.com/102131636/178450719-21aa5f75-4f31-4336-abf6-354d524a6c61.png)

**Expected result:**
Square box should not come when we select any navigation on the header.

**Comment by sudhanshu0603** [comment]
@ui-amankumar  as discussed from the abhishek, it is coming from third party app and we can use the svg for it, pls discuss it with abhishek.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 Issue fixed

**Comment by sudhanshu0603** [comment]
ok, resolved
