### ISSUE TITLE
When we are clicking on the login icon on the header then it is not clicking.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#7]
**Actual result:**
When we are clicking on the login icon on the header then it is clicking and pop is opening to the left side of the screen.
![image](https://user-images.githubusercontent.com/102131636/178465783-fd1e49ab-d16e-4ad4-93c0-c7c6ceb9c521.png)
![image](https://user-images.githubusercontent.com/102131636/178466191-8f27b6b9-6e39-45e9-80da-8065765ba227.png)

**Expected result:**
The login icon have to be clickable on the header below it.

**Comment by devAbhishekYadav** [comment]
@sudhanshu0603 its a designing issue pls assign Aman to it.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 it will resolved please check

**Comment by sudhanshu0603** [comment]
ok, resolved
