### ISSUE TITLE
When we click on the search icon on the header then the cross symbol is coming on the header is not looking good, it can be improved.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/The-Daily-outfit#9]
**Actual result:**
When we click on the search icon on the header then the cross symbol is coming on the header is not looking good, it can be improved.
![image](https://user-images.githubusercontent.com/102131636/178467751-b535636d-93ee-4572-a9f7-490ef5a7aef1.png)

**Expected result:**
The cross symbol have to improved.

**Comment by ui-amankumar** [comment]
@sudhanshu0603 need to check it from the developer end because it is working via click event

**Comment by devAbhishekYadav** [comment]
@ui-amankumar  I have made the changes as you told me to do
@sudhanshu0603 pls retest

**Comment by sudhanshu0603** [comment]
ok, resolved
